### PR TITLE
Add `dittoSpatial()` function for plotting spatial transcriptomics data

### PR DESCRIPTION
**Pull request by dtm2451**
Function will provide easy plotting of spatial transcriptomics data with spots/cells arranged by their x/y coordinates and overlaid on tissue images (when available).

Initially, it will rely only on the `SpatialExperiment` and `VisiumExperiment` structures (which extend the `SingleCellExperiment`) of the Bioconductor SpatialExperiment package for data structure, at least initially.  Seurat compatibility to likely come in a future PR.

(Still needs some work before it will actually be functional, but getting the PR going!)

### CODE REVIEW

**Comment by dtm2451** [comment]
The setup is similar to how `dittoDimPlot()` works:

1. `dittoSpatial()` obtains and preps X, Y, image, and split.by data.
2. This data is then passed along to `dittoScatterPlot()`, which obtains remaining data needs and builds the plot. Such plot building includes use of a `.geom_spatial()` ('.' added, but credit: 10x) to add tissue images as the bottom layer.
3. Plot and underlying data are all passed back to `dittoSpatial()` to allow for additional spatial-specific plot modifications to be added before output.

Finalization will require a bit more knowledge of the typical `Spatial`/`VisiumExperiment` workflow, but the plan is:

- [ ] Have a `samples.use` or `slices.use` input which works similar to cells.use, just referring to groups of cells/spots that are part of the same tissue slice.
- [ ] `Have a samples.meta` or `slices.meta` that defaults to "sample_id" or whatever is the typical metadata slot for such information.
- [ ] The `split.by` input of this function will then default to this `samples`/`slices.meta` so that the default working method will be to make spatial plots of ALL slices, faceted separately.
- [ ] Also have an `images.use` meta which puts to which images for the slices to use, like low-res versus high res, but this plan may need to be updated based on how images are actually stored. Unsure if this plan vs how images are stored is fully compatible. Plan would require images to have an associated sample/slice-id.

**Review by friedue — COMMENTED** [review]
In practice, I don't find myself printing the tissue slide very often underneath the actual scatter plot because the resolution of the tissue slides is usually poor and the spots that contain the info I want to see (e.g. gene expression) obscure the information anyway. 
The spaceRanger output has a clever trick where the opacity of the dots can be adjusted interactively; I assume there must be a way via plotly. But for static images I would make the retrieval and printing of the tissue slide optional.

A feature that I've found helpful is to allow for adjustments of brightness and saturation of the tissue image.
The default settings in the function below would not alter the image and would simply print  the result of the "adjustment" to the screen. 

```
#' @param brightness modulation of brightness as percentage of the current value
#'  (100 for no change)
#' @param saturation modulation of saturation as percentage of the current value
#'  (100 for no change)
#' @param hue modulation of hue is an absolute rotation of -180 degrees to +180
#' degrees from the current position corresponding to an argument range of 0 to
#' 200 (100 for no change)
#' @param ... additional parameters for \code{\link{magick::image_modulate}}
#' @return Returns an object that can be turned into a grob for tibble just like from read.bitmap()
adjust_image <- function(image_path,brightness = 100, saturation = 100, hue = 100, testing_mods = TRUE){
    ori <- magick::image_read(image_path) # this would replace read.bitmap()
    mod <- magick::image_modulate(ori,
        brightness = brightness,
        saturation = saturation,
        hue = hue, ...)

    if(testing_mods == TRUE){
        print(mod)
        return()
    }else{
        return(mod)
    }
 }
```

Maybe this could be added around line #117 of dittoSpatial.R

**Comment by dtm2451** [comment]
- [ ] Consider adding direct support for imgData(ve)$data$url
- [ ] Add image brightness adjustment inputs & code.

**Comment by dtm2451** [comment]
Pausing this PR as I've not had the time to follow up, but there's a lot of great work started here and I do hope to be able to come back and finish it up in the future!

**Pull request closed without merging**
